export const CART_ADDITEM = "CART/ADD_ITEM";
export const CART_DELETEITEM = "CART/DELETE_ITEM";
export const CART_INCREASEQUANTITY = "CART/INCREASEQUANTITY";
export const CART_DECREASEQUANTITY = "CART/DECREASEQUANTITY";
